### ISSUE TITLE
Materialen kwijt / tags are not working properly

### ISSUE THREAD

**Issue by AnnevanMourik** [martijnbentum/heritages#146]
Hi Martijn,
Ik denk dat ik ooit verandering heb aangebracht in de tags van de 'famines', waardoor sommige dingen nu volgens mij in de war zijn. Kan het zijn dat er vertraging zit in hoe het uiteindelijk bij Tiles komt te staan? 
Bijv: Als ik 'berlin airlift' in typ krijg ik 'a woman in berlin' te zien (niet de airlift) en hoewel deze gecategoriseerd staat onder German Hunger WWII, staat er nu links in m'n scherm German Hunger WWI. Weet jij hoe dit kan?

**Comment by martijnbentum** [comment]
(Charley)

It seems that when I have the repository tab open on my laptop, but am inactive for a while (say an hour) and then go back to the tab and add materials, these are not actually processed and added to the repository. If I then manually log out and log in again, I can add. Would it be possible to add a 'forced' log out after inactivity, so that it is clear when we are actually logged out of the session and cannot add materials anymore? Yesterday I thought I added several things, but was actually logged out and hence the materials weren't processed.

Thank you!

Ik zie nu inderdaad dat de materialen er in staan, maar niet verschijnen als ik op de hongersnood (Great Hunger Years) klik. Ik zie ze alleen tussen ‘film’ staan. Het gaat om de 2 video’s links onder in het screenshot, en zie zoals je ziet niet verschijnen als ik ‘Great Hunger Years’ aangeef, al heb ik ze daar wel onder ‘gelist’.

**Comment by martijnbentum** [comment]
Dank voor je mail! 
Hierbij wat verheldering: ik heb ooit een 'famine' German Hunger 1945-49 gehad en die bij sommige al bestaande items gezet die vielen onder 'German hunger WWII'. Ik zie nu dat er wat ingevoerde items nog niet helemaal juist staan en vroeg me af of dat daar aan lag. Een vb. in de bijlage: Hoewel het item 'Der Insulaner verliert die Ruh...' gelabeld is onder 'German Hunger WWII, staat het in het tile view onder 'German Hunger WWI'. 

De derde screenshot is een van de voorbeelden die ik niet zo goed terug kan vinden: 'Überlebensmittel'. Hoewel deze wel getagd is onder Famine 'German Hunger WWII' zie ik 'm er bij tile view niet bij staan - of ligt dat aan mij? (grote kans dat ik iets fout doe)
​
De derde screenshot is een item wat ik heb toegevoegd onder 'German Hunger WWI' en ik zal iets in de tekst over 'Brotlaib' hebben gezegd. Ik weet nog dat ik het onder 'poezie' heb geplaatst (dat deed het archief waar ik het vandaan had ook). Ik zie dit item alleen nu ook niet terug onder tile view. 

Mocht ik hier dingen over het hoofd zien of iets onhandig hebben ingevuld - sorry daarvoor! 

Bedankt voor het 
![Screenshot 2022-10-06 at 11 30 00](https://user-images.githubusercontent.com/19554953/194287203-9cc82ae6-86a3-4a47-ac61-e62105db4876.png)
meedenken en tot gauw,
![Screenshot 2022-10-06 at 10 59 35](https://user-images.githubusercontent.com/19554953/194287170-5c66f31f-f634-4554-b262-807b1187b665.png)
![Screenshot 2022-10-06 at 11 23 00](https:/
![Screenshot 2022-10-06 at 11 22 43](https://user-images.githubusercontent.com/19554953/194287194-e5c82d54-bce8-4140-8de9-54e944495eb2.png)
/user-images.githubusercontent.com/19554953/194287184-2212c3ce-5c12-4cec-b21f-c31ea3f92157.png)

**Comment by martijnbentum** [comment]
De labels worden niet direct aangepast om het zoeken te versnellen. Daarom waren ze niet direct zichtbaar in het overzicht. Een dag later  waren de instances ook zichtbaar onder de correcte labels in het zoekoverzicht
