### ISSUE TITLE
English titles

### ISSUE THREAD

**Issue by IngriddeZ** [martijnbentum/heritages#155]
Zou je Engelse titels default in search functie kunnen maken (ipv titels in originele taal)? (Overlegd met team).

**Comment by martijnbentum** [comment]
Hoi Ingrid,

Er zijn nu 275 entries waarbij het veld engelse titel leeg is. Ik heb ze hieronder toegevoegd. Zover ik kan zien zijn het allemaal wel Engelse titels, die dan alleen in het veld original title zijn ingevuld.

-Zal ik ze automatisch overnemen in het veld engelse titel? Of willen jullie dat liever handmatig doen en controleren voor de zekerheid?
-Zal het ik het veld engelse titel verplicht maken in het toevoegformulier? (Ik denk dat dat wel aan te raden is)

Groet,
Martijn

<Film: Bitter Harvest>,
<Film: Mr. Jones>,
<Film: Death or Canada>,
<Film: Knocknagow>,
<Film: Harvest of Despair>,
<Film: The last shot>,
<Film: The hungry of Holland>,
<Film: Great Famine in the Skibbereen and Schull Workhouses>,
<Film: Widow Lynch Dies in Famine Skibbereen>,
<Film: Famine in Skibbereen - road relief works>,
<Film: Holodomor Survivors: Natalia Avramenko (Ilchenko)>,
<Film: Holodomor Survivors: Maria Boratynska (nee Myshalov)>,
<Film: Holodomor Survivors: Vera Stefaniuk (Dubeyko)>,
<Film: Holodomor Survivors: Yulia Woychyshyn (Stepanenko)>,
<Film: Holodomor Survivors: Wasyl Wasko>,
<Film: Starving for Total War - Turnip Winter 1916 - Special>,
<Film: Strife Torn Greece Gets Food Relief>,
<Film: Pettuleipä Finnish PINE BARK Bread Recipe>,
<Film: UCRDC: Children of Holodomor Survivors - Ludmilla Temertey>,
<Film: Covering the Holodomor: Memory Eternal>,
<Film: The Song Of The Harvesters Of The Ukraine>,
<Film: Famine Mass Graves at Abbystrowry Skibbereen>,
<Film: The Great Irish Famine: Remember Skibbereen>,
<Film: Famine in Skibbereen - Dr Dan helps Widow Keating>,
<Image: Bernardina Curiel carrying 24 loaves of homemade bread to the local bakery, in order to bake them (I)>,
<Image: A market scene with women haggling>,
<Image: Woman Selling Tomatoes>,
<Image: Harvest, Winnowing Grain>,
<Image: Another Piteous Wail from the Land of English-Made Famines>,
<Image: Young girls eating>,
<Image: Unidentified men and child eating>,
<Image: View of Barranco de las Conejeras (The Rabbit Warren)>,
<Image: Alan Lomax (second left of man in doorway) with crowd>,
<Image: Family in front of hillside dwelling>,
<Image: Young girl with messy face>,
<Image: Children in village square (I)>,
<Image: Children in village square (II)>,
<Image: Parents with baby>,
<Image: Woman nursing in village square>,
<Image: Fruit stand at street market>,
<Image: Two women in boathouse (I)>,
<Image: Two women in boathouse (II)>,
<Image: Cheese shop>,
<Image: Beggarwoman on road to Madrid (III)>,
<Image: Beggarwoman on road to Madrid (II)>,
<Image: Unidentified girl>,
<Image: Unidentified woman and children>,
<Image: Unidentified woman with basket>,
<Image: Old woman selling potatoes>,
<Image: Beggarwoman on rode to Madrid (I)>,
<Image: Farmers and children at mealtime>,
<Image: FORBIDDEN. Kharkov. Peasants waiting for a train. Abbe arrested for this.>,
<Image: Pigs in garbage dump>,
<Image: Garbage scavenger>,
<Image: Discovery of the Potato Blight In Ireland>,
<Image: Judy O'Donnel's Habitation Under the Bridge at Doonbeg>,
<Image: An Ejectment in Ireland (A Tear and a Prayer for Erin)>,
<Image: The Widow Connor and her Dying Child>,
<Image: No title>,
<Image: No title>,
<Image: No title>,
<Image: No title>,
<Image: No title>,
<Image: No title>,
<Image: No title>,
<Image: Hugh Boulter>,
<Image: Two old women in doorway>,
<Image: Mercando pan>,
<Image: Union is Strength.>,
<Image: Justice to Ireland.>,
<Image: Carrying the Corn; Or, The Free-Trade Harvest-Home.>,
<Image: Commemorative Manifestation Poster>,
<Image: War 1939-45. Macedonia, Thessalonica. Registration for milk distribution.>,
<Image: War 1939-45. Macedonia, Thessalonica. Woman with child begging in the street.>,
<Image: War 1939-45. Macedonia, Thessalonica, Scolioni street. Soup for the children.>,
<Image: A dekulakized family near their house in Udachne village, Donetsk region>,
<Image: No title>,
<Image: No title>,
<Image: Breast-feeding at a milk distribution center.>,
<Image: Mess at the “Drapetsona Shelter”>,
<Infographic: The Our World in Data Dataset of Famines>,
<Infographic: Population by Country (Island of Ireland Figures), 1500 to 2000>,
<Infographic: Famine as main reason for emigration? (total 28)>,
<Memorialsite: Zuiderkerk Amsterdam>,
<Memorialsite: Manna>,
<Memorialsite: The Obelisk, Conolly's Folly, Baois Uí Chongaile>,
<Memorialsite: National Famine Memorial / Coffin Ship>,
<Memorialsite: Holodomor Monument Edmonton>,
<Memorialsite: Holodomor Monument Winnipeg>,
<Memorialsite: Famine>,
<Memorialsite: Arrival>,
<Memorialsite: Broken Heart Fountain>,
<Memorialsite: Australian Monument to the Great Irish Famine>,
<Memorialsite: Famine Memorial>,
<Memorialsite: Famine Memorial>,
<Memorialsite: Celtic Cross>,
<Memorialsite: Faoin Sceach>,
<Memorialsite: Famine Family>,
<Memorialsite: Ireland Park>,
<Memorialsite: Holodomor Monument Windsor>,
<Memorialsite: Holodomor Statue Regina>,
<Memorialsite: Holodomor Memorial Parkette>,
<Memorialsite: Los Angeles Holodomor Monument>,
<Memorialsite: Holodomor Monument Canberra>,
<Memorialsite: Holodomor Monument Chicago>,
<Memorialsite: Uusikylä (Arola) [Nastola]>,
<Memorialsite: Holodomor Memorial to Victims of the Ukrainian Famine-Genocide of 1932–1933>,
<Memorialsite: Memorial sign of the city of Volochysk>,
<Memorialsite: Holodomor Memorial>,
<Memorialsite: Jämsä memorial>,
<Memorialsite: Lehtimäki memorial>,
<Music: The Coffin Ships>,
<Music: Thousands are Sailing>,
<Music: The City of Chicago>,
<Music: The Gift>,
<Music: The Fields of Athenry>,
<Music: Black 47>,
<Music: The New Ground - Isle of Hope, Isle of Tears>,
<Music: Lough Sheelin Eviction>,
<Music: Spancil Hill>,
<Music: Mountains O' Mourne>,
<Music: The Famine Song>,
<Music: The Coffin Ships>,
<Music: Skibbereen>,
<Music: Along the Western Seaboard>,
<Music: Buried in the Deep>,
<Music: Poor Boy's Shoes>,
<Music: Indian Meal>,
<Music: Laissez faire>,
<Music: Rattle My Bones>,
<Music: Villain Curry Shaw>,
<Music: Johnny and the Lantern>,
<Music: The Connaught Orphan>,
<Music: The Great Saint Lawrence River>,
<Music: Edward Connors>,
<Music: Come To The Land Of Sweet Liberty>,
<Music: Farewell To Old Ireland>,
<Music: Sailing Off to the Yankee Land>,
<Music: Sally Grier>,
<Music: Pat Maguire>,
<Music: The Green Fields of America>,
<Music: Erin's Lovely Home>,
<Music: Poor Pat Must Emigrate>,
<Music: Dear Little Shamrock Shore>,
<Music: Shamrock Shore>,
<Music: By The Hush>,
<Music: No Irish Need Apply>,
<Music: Rigged Out>,
<Music: Lone Shanakyle>,
<Music: Thousands Are Sailing to Amerikay>,
<Music: My Own Dear Galway Bay>,
<Music: The Praties They Grow Small>,
<Music: Dan O'Hara>,
<Music: Poor Paddy>,
<Music: I'll Take You Home Again, Kathleen>,
<Music: Famine>,
<PictureStory: Black '47: A Story of Ireland's Great Famine>,
<PictureStory: Go Home Paddy>,
<PictureStory: Gone to Amerikay>,
<PictureStory: The Long March: The Choctaw's Gift to Irish Famine Relief>,
<Text: Star of the Sea>,
<Text: Mike: a Tale of the Irish Famine>,
<Text: Grace>,
<Text: Famine Roads and Famine Memories>,
<Text: The Hungry Death>,
<Text: Jonathan Swift to Mrs. Whiteway, 31 December 1740>,
<Text: Jonathan Swift to Mrs. Whiteway, 3 February 1739-40>,
<Text: Extract of a Letter from Cork in Ireland>,
<Text: From the Gazetteer>,
<Text: IRELAND, Drogheda, 18 April>,
<Text: The Groans of Ireland: In a Letter to a Member of Parliament>,
<Text: The Necessity of Tillage and Granaries. In a Letter to a Member of Parliament living in the County of ---->,
<Text: The Judgments of God upon Ireland, or Sickness and famine God's visitation: for the Sins of the Nation>,
<Text: God's method of visiting a sinful people: A Sermon Preach'd at St. Andrew's Dublin, before the Honourable the House of Commons, on Wednesday, November 25th. 1741>,
<Text: Extract of a Letter from Paris, Dec. 11>,
<Text: EXTRAORDINARY LONGEVITY>,
<Text: SINGULAR PHENOMENON>,
<Text: An Elegy>,
<Text: To Francis Bindon, Esq; On a picture of His Grace Dr. Hugh Boulter, Lord Arch-Bishop of Armagh, set up in the work-house, near Dublin, in commemoration of his charities in the years 1739-40 and 1740-41>,
<Text: The Frosty Winters of Ireland in the years 1739/40>,
<Text: Famine: A Poem>,
<Text: On the late Thaw>,
<Text: STATE OF IRELAND, 7 February 1846>,
<Text: STATE OF IRELAND, 28 January 1847>,
<Text: IRELAND, 26 April 1848>,
<Text: The Irish Crisis>,
<Text: The Great Famine in Ireland and a Retrospect of the Fifty Years 1845–1895, with a Sketch of the Present Condition and Future Prospects of the Congested Districts>,
<Text: The History of the Great Irish Famine of 1847, with Notices of Earlier Irish Famines>,
<Text: George Berkeley to George Faulkner, 17 February 1741>,
<Text: George Berkeley to Thomas Prior, 19 May 1741>,
<Text: The Hungry Death>,
<Text: Letter of Charles Edward Trevelyan to Thomas Spring-Rice, Lord Mounteagle>,
<Text: Troost der armen. Een lied in hunne woning. Kerstavond 1845>,
<Text: Een bedelbrief in den winter>,
<Text: The Famine>,
<Text: The Countess Cathleen>,
<Text: Dawn>,
<Text: Famine>,
<Text: Souper Sullivan>,
<Text: The Sugar Wife>,
<Text: Belfast Girls>,
<Text: The Famine Year>,
<Text: The Voice of the Poor>,
<Text: The Passing of the Gael>,
<Text: Irish Demands Upon the Government.>,
<Text: Irish Landlords and the Distress.>,
<Text: Indolent Preference of Relief to Labour.>,
<Text: Irish Landlords.>,
<Text: The Duty of the Government.>,
<Text: Food Exports from Ireland to England.>,
<Text: State Aid to Public Works.>,
<Text: Reliance on State Help.>,
<Text: Neglect of Available Food Supplies.>,
<Text: The Irish Saving Banks.>,
<Text: Landlords and Labour.>,
<Text: Landlords and the Poor Law.>,
<Text: Landlords' Objections to a Poor Law.>,
<Text: Irish Objection to Poor Law.>,
<Text: Irish Property and Irish Poverty.>,
<Text: Irish Unanimity.>,
<Text: Cost of Relief.>,
<Text: Government and Irish Railways.>,
<Text: General Apathy in Ireland>,
<Text: State of Skibbereen.>,
<Text: The Poor Relief Bill.>,
<Text: The Day of National Humiliation.>,
<Text: Proposal for Irish Colonisation in Canada.>,
<Text: The Famine of 1741.>,
<Text: The New Irish Poor Law.>,
<Text: Subsidence of the Distress>,
<Text: Closing of the Relief Fund.>,
<Text: Magnitude of Relief Operations.>,
<Text: Horrors of the Exodus to Canada.>,
<Text: Resistance to Poor's Rates.>,
<Text: Irish Emigration.>,
<Text: Landlord Murders.>,
<Text: Emigration as a Remedy for Irish Property.>,
<Text: Disorder in Ireland.>,
<Text: The Irish Fisheries.>,
<Text: Clerical Encouragement of Murder.>,
<Text: The Need of Common Sense.>,
<Text: The Value of an Irish Poor Law.>,
<Text: Agricultural Instruction in Ireland.>,
<Text: Landlord Ejectment from Ireland.>,
<Text: A Prophecy from the Potato.>,
<Text: How to Cure Ireland.>,
<Text: The Nation We Cannot Subdue.>,
<Text: Castle Daly; The Story of an Irish Home Thirty Years Ago>,
<Text: The Chronicles of Castle Cloyne; Or, Pictures of the Munster People>,
<Text: A Visit to Connaught in the Autumn of 1847. A Letter Addressed to the Central Relief Committee of the Society of Friends, Dublin>,
<Text: Quarantine>,
<Text: After the Famine>,
<Text: Winterkill>,
<Text: Maniak Collection: Mysak Pavlo>,
<Text: Maniak Collection: Voznytsia (Makukh) Natalia>,
<Text: Maniak Collection: Khurdei Oleksii (Aleksei)>,
<Text: Death Certificate of Konstantin Bokan>,
<Text: Maniak Collection: Mazepa Hanna>,
<Text: 3.000.000 Starved Peasants Die In Ukraine in Less Than Year>,
<Text: Ukraine Collectives Have Best Harvest in 30 Years>,
<Text: Anti-Soviet Lies>,
<Text: Woman Writer Ordered out by Soviet Russia>,
<Text: Delibrate Famine in Russia>,
<Text: The Soviet and the peasantry: hunger in Ukraine>,
<Text: Famine Faces a Million in Spain>,
<Text: Threat of Famine Reported by Dutch; Will Ask UNRRA Aid>,
<Text: 3,200,000 in Holland Faced By Starvation>,
<Text: When the tree sings>,
<Text: Famine, Starvation, Suffering Faced By Millions In Europe>,
<Text: Red Cross Links Detroiters to Kin>,
<Text: Famine abroad>,
<Text: Famine in Finland>,
<Text: The Famine in Finland>,
<Text: The Famine in Finland>,
<Videogame: This War of Mine>

**Comment by IngriddeZ** [comment]
Ha Martijn,

Bedankt voor je berichtjes. Ik was het ondertussen aan het uitzoeken met Helmi en wij kwamen tot dezelfde conclusie.

Misschien zou je bij de entries die er nu al instaan ze automatisch overnemen in het veld 'Engelse titel', en het daarna inderdaad een verplicht veld maken? Dan zou het in vervolg geen probleem meer moeten zijn.

Als dat niet lukt, dan moeten we die 275 inderdaad even handmatig overzetten. Ik zet Lindsay in de cc zodat ze ook op de hoogte is en dit evt in de volgende vergadering op de agenda kan zetten.

Veel dank!
Ingrid



________________________________
Van: martijnbentum ***@***.***>
Verzonden: donderdag 27 oktober 2022 13:18
Aan: martijnbentum/heritages ***@***.***>
CC: Zwarte, Ingrid de ***@***.***>; Author ***@***.***>
Onderwerp: Re: [martijnbentum/heritages] English titles (Issue #155)


Hoi Ingrid,

Er zijn nu 275 entries waarbij het veld engelse titel leeg is. Ik heb ze hieronder toegevoegd. Zover ik kan zien zijn het allemaal wel Engelse titels, die dan alleen in het veld original title zijn ingevuld.

-Zal ik ze automatisch overnemen in het veld engelse titel? Of willen jullie dat liever handmatig doen en controleren voor de zekerheid?
-Zal het ik het veld engelse titel verplicht maken in het toevoegformulier? (Ik denk dat dat wel aan te raden is)

Groet,
Martijn

<Film: Bitter Harvest>,
<Film: Mr. Jones>,
<Film: Death or Canada>,
<Film: Knocknagow>,
<Film: Harvest of Despair>,
<Film: The last shot>,
<Film: The hungry of Holland>,
<Film: Great Famine in the Skibbereen and Schull Workhouses>,
<Film: Widow Lynch Dies in Famine Skibbereen>,
<Film: Famine in Skibbereen - road relief works>,
<Film: Holodomor Survivors: Natalia Avramenko (Ilchenko)>,
<Film: Holodomor Survivors: Maria Boratynska (nee Myshalov)>,
<Film: Holodomor Survivors: Vera Stefaniuk (Dubeyko)>,
<Film: Holodomor Survivors: Yulia Woychyshyn (Stepanenko)>,
<Film: Holodomor Survivors: Wasyl Wasko>,
<Film: Starving for Total War - Turnip Winter 1916 - Special>,
<Film: Strife Torn Greece Gets Food Relief>,
<Film: Pettuleipä Finnish PINE BARK Bread Recipe>,
<Film: UCRDC: Children of Holodomor Survivors - Ludmilla Temertey>,
<Film: Covering the Holodomor: Memory Eternal>,
<Film: The Song Of The Harvesters Of The Ukraine>,
<Film: Famine Mass Graves at Abbystrowry Skibbereen>,
<Film: The Great Irish Famine: Remember Skibbereen>,
<Film: Famine in Skibbereen - Dr Dan helps Widow Keating>,
<Image: Bernardina Curiel carrying 24 loaves of homemade bread to the local bakery, in order to bake them (I)>,
<Image: A market scene with women haggling>,
<Image: Woman Selling Tomatoes>,
<Image: Harvest, Winnowing Grain>,
<Image: Another Piteous Wail from the Land of English-Made Famines>,
<Image: Young girls eating>,
<Image: Unidentified men and child eating>,
<Image: View of Barranco de las Conejeras (The Rabbit Warren)>,
<Image: Alan Lomax (second left of man in doorway) with crowd>,
<Image: Family in front of hillside dwelling>,
<Image: Young girl with messy face>,
<Image: Children in village square (I)>,
<Image: Children in village square (II)>,
<Image: Parents with baby>,
<Image: Woman nursing in village square>,
<Image: Fruit stand at street market>,
<Image: Two women in boathouse (I)>,
<Image: Two women in boathouse (II)>,
<Image: Cheese shop>,
<Image: Beggarwoman on road to Madrid (III)>,
<Image: Beggarwoman on road to Madrid (II)>,
<Image: Unidentified girl>,
<Image: Unidentified woman and children>,
<Image: Unidentified woman with basket>,
<Image: Old woman selling potatoes>,
<Image: Beggarwoman on rode to Madrid (I)>,
<Image: Farmers and children at mealtime>,
<Image: FORBIDDEN. Kharkov. Peasants waiting for a train. Abbe arrested for this.>,
<Image: Pigs in garbage dump>,
<Image: Garbage scavenger>,
<Image: Discovery of the Potato Blight In Ireland>,
<Image: Judy O'Donnel's Habitation Under the Bridge at Doonbeg>,
<Image: An Ejectment in Ireland (A Tear and a Prayer for Erin)>,
<Image: The Widow Connor and her Dying Child>,
<Image: No title>,
<Image: No title>,
<Image: No title>,
<Image: No title>,
<Image: No title>,
<Image: No title>,
<Image: No title>,
<Image: Hugh Boulter>,
<Image: Two old women in doorway>,
<Image: Mercando pan>,
<Image: Union is Strength.>,
<Image: Justice to Ireland.>,
<Image: Carrying the Corn; Or, The Free-Trade Harvest-Home.>,
<Image: Commemorative Manifestation Poster>,
<Image: War 1939-45. Macedonia, Thessalonica. Registration for milk distribution.>,
<Image: War 1939-45. Macedonia, Thessalonica. Woman with child begging in the street.>,
<Image: War 1939-45. Macedonia, Thessalonica, Scolioni street. Soup for the children.>,
<Image: A dekulakized family near their house in Udachne village, Donetsk region>,
<Image: No title>,
<Image: No title>,
<Image: Breast-feeding at a milk distribution center.>,
<Image: Mess at the “Drapetsona Shelter”>,
<Infographic: The Our World in Data Dataset of Famines>,
<Infographic: Population by Country (Island of Ireland Figures), 1500 to 2000>,
<Infographic: Famine as main reason for emigration? (total 28)>,
<Memorialsite: Zuiderkerk Amsterdam>,
<Memorialsite: Manna>,
<Memorialsite: The Obelisk, Conolly's Folly, Baois Uí Chongaile>,
<Memorialsite: National Famine Memorial / Coffin Ship>,
<Memorialsite: Holodomor Monument Edmonton>,
<Memorialsite: Holodomor Monument Winnipeg>,
<Memorialsite: Famine>,
<Memorialsite: Arrival>,
<Memorialsite: Broken Heart Fountain>,
<Memorialsite: Australian Monument to the Great Irish Famine>,
<Memorialsite: Famine Memorial>,
<Memorialsite: Famine Memorial>,
<Memorialsite: Celtic Cross>,
<Memorialsite: Faoin Sceach>,
<Memorialsite: Famine Family>,
<Memorialsite: Ireland Park>,
<Memorialsite: Holodomor Monument Windsor>,
<Memorialsite: Holodomor Statue Regina>,
<Memorialsite: Holodomor Memorial Parkette>,
<Memorialsite: Los Angeles Holodomor Monument>,
<Memorialsite: Holodomor Monument Canberra>,
<Memorialsite: Holodomor Monument Chicago>,
<Memorialsite: Uusikylä (Arola) [Nastola]>,
<Memorialsite: Holodomor Memorial to Victims of the Ukrainian Famine-Genocide of 1932–1933>,
<Memorialsite: Memorial sign of the city of Volochysk>,
<Memorialsite: Holodomor Memorial>,
<Memorialsite: Jämsä memorial>,
<Memorialsite: Lehtimäki memorial>,
<Music: The Coffin Ships>,
<Music: Thousands are Sailing>,
<Music: The City of Chicago>,
<Music: The Gift>,
<Music: The Fields of Athenry>,
<Music: Black 47>,
<Music: The New Ground - Isle of Hope, Isle of Tears>,
<Music: Lough Sheelin Eviction>,
<Music: Spancil Hill>,
<Music: Mountains O' Mourne>,
<Music: The Famine Song>,
<Music: The Coffin Ships>,
<Music: Skibbereen>,
<Music: Along the Western Seaboard>,
<Music: Buried in the Deep>,
<Music: Poor Boy's Shoes>,
<Music: Indian Meal>,
<Music: Laissez faire>,
<Music: Rattle My Bones>,
<Music: Villain Curry Shaw>,
<Music: Johnny and the Lantern>,
<Music: The Connaught Orphan>,
<Music: The Great Saint Lawrence River>,
<Music: Edward Connors>,
<Music: Come To The Land Of Sweet Liberty>,
<Music: Farewell To Old Ireland>,
<Music: Sailing Off to the Yankee Land>,
<Music: Sally Grier>,
<Music: Pat Maguire>,
<Music: The Green Fields of America>,
<Music: Erin's Lovely Home>,
<Music: Poor Pat Must Emigrate>,
<Music: Dear Little Shamrock Shore>,
<Music: Shamrock Shore>,
<Music: By The Hush>,
<Music: No Irish Need Apply>,
<Music: Rigged Out>,
<Music: Lone Shanakyle>,
<Music: Thousands Are Sailing to Amerikay>,
<Music: My Own Dear Galway Bay>,
<Music: The Praties They Grow Small>,
<Music: Dan O'Hara>,
<Music: Poor Paddy>,
<Music: I'll Take You Home Again, Kathleen>,
<Music: Famine>,
<PictureStory: Black '47: A Story of Ireland's Great Famine>,
<PictureStory: Go Home Paddy>,
<PictureStory: Gone to Amerikay>,
<PictureStory: The Long March: The Choctaw's Gift to Irish Famine Relief>,
<Text: Star of the Sea>,
<Text: Mike: a Tale of the Irish Famine>,
<Text: Grace>,
<Text: Famine Roads and Famine Memories>,
<Text: The Hungry Death>,
<Text: Jonathan Swift to Mrs. Whiteway, 31 December 1740>,
<Text: Jonathan Swift to Mrs. Whiteway, 3 February 1739-40>,
<Text: Extract of a Letter from Cork in Ireland>,
<Text: From the Gazetteer>,
<Text: IRELAND, Drogheda, 18 April>,
<Text: The Groans of Ireland: In a Letter to a Member of Parliament>,
<Text: The Necessity of Tillage and Granaries. In a Letter to a Member of Parliament living in the County of ---->,
<Text: The Judgments of God upon Ireland, or Sickness and famine God's visitation: for the Sins of the Nation>,
<Text: God's method of visiting a sinful people: A Sermon Preach'd at St. Andrew's Dublin, before the Honourable the House of Commons, on Wednesday, November 25th. 1741>,
<Text: Extract of a Letter from Paris, Dec. 11>,
<Text: EXTRAORDINARY LONGEVITY>,
<Text: SINGULAR PHENOMENON>,
<Text: An Elegy>,
<Text: To Francis Bindon, Esq; On a picture of His Grace Dr. Hugh Boulter, Lord Arch-Bishop of Armagh, set up in the work-house, near Dublin, in commemoration of his charities in the years 1739-40 and 1740-41>,
<Text: The Frosty Winters of Ireland in the years 1739/40>,
<Text: Famine: A Poem>,
<Text: On the late Thaw>,
<Text: STATE OF IRELAND, 7 February 1846>,
<Text: STATE OF IRELAND, 28 January 1847>,
<Text: IRELAND, 26 April 1848>,
<Text: The Irish Crisis>,
<Text: The Great Famine in Ireland and a Retrospect of the Fifty Years 1845–1895, with a Sketch of the Present Condition and Future Prospects of the Congested Districts>,
<Text: The History of the Great Irish Famine of 1847, with Notices of Earlier Irish Famines>,
<Text: George Berkeley to George Faulkner, 17 February 1741>,
<Text: George Berkeley to Thomas Prior, 19 May 1741>,
<Text: The Hungry Death>,
<Text: Letter of Charles Edward Trevelyan to Thomas Spring-Rice, Lord Mounteagle>,
<Text: Troost der armen. Een lied in hunne woning. Kerstavond 1845>,
<Text: Een bedelbrief in den winter>,
<Text: The Famine>,
<Text: The Countess Cathleen>,
<Text: Dawn>,
<Text: Famine>,
<Text: Souper Sullivan>,
<Text: The Sugar Wife>,
<Text: Belfast Girls>,
<Text: The Famine Year>,
<Text: The Voice of the Poor>,
<Text: The Passing of the Gael>,
<Text: Irish Demands Upon the Government.>,
<Text: Irish Landlords and the Distress.>,
<Text: Indolent Preference of Relief to Labour.>,
<Text: Irish Landlords.>,
<Text: The Duty of the Government.>,
<Text: Food Exports from Ireland to England.>,
<Text: State Aid to Public Works.>,
<Text: Reliance on State Help.>,
<Text: Neglect of Available Food Supplies.>,
<Text: The Irish Saving Banks.>,
<Text: Landlords and Labour.>,
<Text: Landlords and the Poor Law.>,
<Text: Landlords' Objections to a Poor Law.>,
<Text: Irish Objection to Poor Law.>,
<Text: Irish Property and Irish Poverty.>,
<Text: Irish Unanimity.>,
<Text: Cost of Relief.>,
<Text: Government and Irish Railways.>,
<Text: General Apathy in Ireland>,
<Text: State of Skibbereen.>,
<Text: The Poor Relief Bill.>,
<Text: The Day of National Humiliation.>,
<Text: Proposal for Irish Colonisation in Canada.>,
<Text: The Famine of 1741.>,
<Text: The New Irish Poor Law.>,
<Text: Subsidence of the Distress>,
<Text: Closing of the Relief Fund.>,
<Text: Magnitude of Relief Operations.>,
<Text: Horrors of the Exodus to Canada.>,
<Text: Resistance to Poor's Rates.>,
<Text: Irish Emigration.>,
<Text: Landlord Murders.>,
<Text: Emigration as a Remedy for Irish Property.>,
<Text: Disorder in Ireland.>,
<Text: The Irish Fisheries.>,
<Text: Clerical Encouragement of Murder.>,
<Text: The Need of Common Sense.>,
<Text: The Value of an Irish Poor Law.>,
<Text: Agricultural Instruction in Ireland.>,
<Text: Landlord Ejectment from Ireland.>,
<Text: A Prophecy from the Potato.>,
<Text: How to Cure Ireland.>,
<Text: The Nation We Cannot Subdue.>,
<Text: Castle Daly; The Story of an Irish Home Thirty Years Ago>,
<Text: The Chronicles of Castle Cloyne; Or, Pictures of the Munster People>,
<Text: A Visit to Connaught in the Autumn of 1847. A Letter Addressed to the Central Relief Committee of the Society of Friends, Dublin>,
<Text: Quarantine>,
<Text: After the Famine>,
<Text: Winterkill>,
<Text: Maniak Collection: Mysak Pavlo>,
<Text: Maniak Collection: Voznytsia (Makukh) Natalia>,
<Text: Maniak Collection: Khurdei Oleksii (Aleksei)>,
<Text: Death Certificate of Konstantin Bokan>,
<Text: Maniak Collection: Mazepa Hanna>,
<Text: 3.000.000 Starved Peasants Die In Ukraine in Less Than Year>,
<Text: Ukraine Collectives Have Best Harvest in 30 Years>,
<Text: Anti-Soviet Lies>,
<Text: Woman Writer Ordered out by Soviet Russia>,
<Text: Delibrate Famine in Russia>,
<Text: The Soviet and the peasantry: hunger in Ukraine>,
<Text: Famine Faces a Million in Spain>,
<Text: Threat of Famine Reported by Dutch; Will Ask UNRRA Aid>,
<Text: 3,200,000 in Holland Faced By Starvation>,
<Text: When the tree sings>,
<Text: Famine, Starvation, Suffering Faced By Millions In Europe>,
<Text: Red Cross Links Detroiters to Kin>,
<Text: Famine abroad>,
<Text: Famine in Finland>,
<Text: The Famine in Finland>,
<Text: The Famine in Finland>,
<Videogame: This War of Mine>

**Comment by martijnbentum** [comment]
Hoi Ingrid,

Ik heb 
-de titels van bovenstaande lijst overgenomen in het veld voor engelse titels.
-het formulier aangepast zodat je nu ook verplicht de engelse title moet invullen

Groet,

**Comment by IngriddeZ** [comment]
Perfect, bedankt Martijn!

Fijn weekend,
Ingrid

________________________________
Van: martijnbentum ***@***.***>
Verzonden: donderdag 27 oktober 2022 15:27
Aan: martijnbentum/heritages ***@***.***>
CC: Zwarte, Ingrid de ***@***.***>; Author ***@***.***>
Onderwerp: Re: [martijnbentum/heritages] English titles (Issue #155)


Hoi Ingrid,

Ik heb
-de titels van bovenstaande lijst overgenomen in het veld voor engelse titels.
-het formulier aangepast zodat je nu ook verplicht de engelse title moet invullen

Groet,
